[package]
name = "parcom"
version = "0.1.0"
authors = ["Erik Bremen <strtok@strtok.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
