name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Cache cargo dependencies
        uses: actions/cache@v1
        with:
          key: ${{ runner.os }}-wasm-${{ hashFiles('**/Cargo.lock') }}
          path: target
          restore-keys: |
            ${{ runner.os }}-wasm-
            
      - name: Setup wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Setup node
        uses: actions/setup-node@v1

      - name: Build wasm 
        run: |
          wasm-pack build
          npm install
        working-directory: ./marwood-wasm

      - name: Compile website
        run: |
          npm install
          npm run build
        working-directory: ./marwood-wasm/www

      - name: Deploy to gh-pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./marwood-wasm/www/dist
          force_orphan: true
